In [1]:
import pandas as pd
import numpy as np

In [2]:
ch1 = pd.read_csv("CH2.csv")

In [3]:
ch1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2617 entries, 0 to 2616
Columns: 5003 entries, ID to label
dtypes: float64(5001), int64(1), object(1)
memory usage: 99.9+ MB

In [4]:
X = ch1.select_dtypes(exclude = "int64")
Y = ch1["label"]

### Data Analysis

#### Labels Histogram

In [5]:
pd.value_counts(Y)

3    387
1    382
2    379
4    377
5    375
6    364
0    353
Name: label, dtype: int64

In [6]:
fft = X.select_dtypes("float64").T

##### Files with infinity components

In [7]:
ch1.loc[np.where(np.max(fft) == np.inf)[0], "ID"]

1673    4_c0354c45c100.csv
Name: ID, dtype: object

In [8]:
finite_X = X.drop(np.where(np.max(fft) == np.inf)[0])
finite_Y = Y.drop(np.where(np.max(fft) == np.inf)[0])

In [9]:
finite_X.iloc[np.where(finite_X.isna().any(axis = 1))[0]]

,ID,0,1,2,3,4,5,6,7,8,...,4991,4992,4993,4994,4995,4996,4997,4998,4999,5000
835,2_c0946c35c000.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1301,3_c1865c45c050.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1302,3_c1866c45c050.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1312,3_c1876c45c050.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1563,4_c0135c35c100.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992,5_c1006c40c100.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2117,5_c1258c50c050.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2146,5_c1321c55c100.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2184,5_c1392c55c000.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2387,6_c1814c40c000.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2397,6_c1824c40c000.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2417,6_c1862c45c100.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
finite_X.iloc[~ np.where(finite_X.isna().any(axis = 1))[0]]

,ID,0,1,2,3,4,5,6,7,8,...,4991,4992,4993,4994,4995,4996,4997,4998,4999,5000
1781,4_c0574c55c100.csv,1.689132,0.000094,0.000053,0.000030,0.000115,0.000228,0.000147,0.000101,0.000090,...,0.000005,0.000042,0.000047,0.000038,0.000051,0.000013,0.000023,0.000016,0.000041,0.000003
1314,3_c1878c45c050.csv,1.695644,0.000063,0.000119,0.000103,0.000098,0.000067,0.000047,0.000139,0.000078,...,0.000018,0.000046,0.000017,0.000023,0.000023,0.000022,0.000035,0.000052,0.000039,0.000028
1313,3_c1877c45c050.csv,1.695932,0.000088,0.000063,0.000068,0.000149,0.000139,0.000202,0.000129,0.000143,...,0.000038,0.000033,0.000053,0.000056,0.000030,0.000077,0.000048,0.000012,0.000041,0.000031
1303,3_c1867c45c050.csv,1.696468,0.000079,0.000064,0.000053,0.000088,0.000441,0.000201,0.000103,0.000180,...,0.000037,0.000024,0.000051,0.000037,0.000065,0.000006,0.000010,0.000042,0.000024,0.000070
1052,2_c1381c55c000.csv,1.686283,0.000023,0.000055,0.000102,0.000072,0.000046,0.000055,0.000039,0.000092,...,0.000018,0.000017,0.000019,0.000017,0.000033,0.000048,0.000014,0.000037,0.000017,0.000076
624,1_c0541c55c100.csv,1.682588,0.000135,0.000108,0.000071,0.000138,0.000200,0.000185,0.000137,0.000138,...,0.000026,0.000015,0.000051,0.000023,0.000036,0.000039,0.000069,0.000042,0.000049,0.000018
499,1_c0283c40c000.csv,1.680289,0.000070,0.000014,0.000083,0.000038,0.000017,0.000102,0.000039,0.000091,...,0.000027,0.000004,0.000013,0.000021,0.000030,0.000039,0.000018,0.000028,0.000010,0.000024
470,1_c0222c40c100.csv,1.674141,0.000099,0.000105,0.000030,0.000012,0.000118,0.000123,0.000019,0.000082,...,0.000013,0.000031,0.000028,0.000035,0.000017,0.000041,0.000038,0.000017,0.000035,0.000015
432,1_c0150c35c050.csv,1.684283,0.000069,0.000060,0.000153,0.000257,0.000255,0.000030,0.000076,0.000168,...,0.000046,0.000020,0.000008,0.000042,0.000035,0.000045,0.000045,0.000022,0.000009,0.000070
229,0_c2493c50c050.csv,1.695998,0.000161,0.000116,0.000145,0.000206,0.000092,0.000194,0.000149,0.000084,...,0.000014,0.000037,0.000049,0.000033,0.000042,0.000024,0.000031,0.000013,0.000039,0.000042
219,0_c2483c50c100.csv,1.688062,0.000067,0.000076,0.000055,0.000095,0.000044,0.000091,0.000120,0.000032,...,0.000080,0.000043,0.000038,0.000008,0.000055,0.000046,0.000022,0.000005,0.000050,0.000061
199,0_c2463c45c000.csv,1.686071,0.000554,0.000146,0.000434,0.000294,0.000372,0.000501,0.000160,0.000229,...,0.000040,0.000017,0.000010,0.000011,0.000030,0.000026,0.000049,0.000047,0.000044,0.000005

In [11]:
finite_Y = finite_Y[~finite_X.isna().any(axis = 1)]
finite_X = finite_X[~finite_X.isna().any(axis = 1)]

In [12]:
finite_X = finite_X.reset_index(drop=True)
finite_Y = finite_Y.reset_index(drop=True)

In [13]:
finite_X

,ID,0,1,2,3,4,5,6,7,8,...,4991,4992,4993,4994,4995,4996,4997,4998,4999,5000
0,0_c2264c30c100.csv,1.688009,0.000057,0.000078,0.000043,0.000203,0.000056,0.000063,0.000159,0.000123,...,0.000026,0.000061,0.000046,0.000024,0.000021,0.000029,0.000039,0.000056,0.000051,0.000007
1,0_c2265c30c100.csv,1.688135,0.000091,0.000088,0.000097,0.000131,0.000042,0.000106,0.000123,0.000078,...,0.000040,0.000015,0.000031,0.000076,0.000010,0.000026,0.000054,0.000038,0.000026,0.000010
2,0_c2266c30c100.csv,1.687388,0.000123,0.000117,0.000136,0.000163,0.000043,0.000021,0.000060,0.000142,...,0.000013,0.000024,0.000073,0.000019,0.000036,0.000049,0.000027,0.000039,0.000034,0.000011
3,0_c2267c30c100.csv,1.689388,0.000015,0.000103,0.000027,0.000093,0.000058,0.000069,0.000020,0.000181,...,0.000024,0.000033,0.000014,0.000029,0.000044,0.000036,0.000046,0.000019,0.000044,0.000051
4,0_c2268c30c100.csv,1.689067,0.000092,0.000112,0.000046,0.000074,0.000095,0.000017,0.000025,0.000041,...,0.000049,0.000019,0.000040,0.000015,0.000025,0.000038,0.000062,0.000012,0.000036,0.000025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2599,6_c2259c60c000.csv,1.682455,0.000025,0.000051,0.000039,0.000032,0.000034,0.000042,0.000051,0.000069,...,0.000065,0.000021,0.000032,0.000033,0.000014,0.000029,0.000012,0.000079,0.000020,0.000092
2600,6_c2260c60c000.csv,1.683159,0.000040,0.000077,0.000068,0.000032,0.000044,0.000078,0.000108,0.000053,...,0.000046,0.000050,0.000028,0.000035,0.000058,0.000034,0.000027,0.000068,0.000032,0.000108
2601,6_c2261c60c000.csv,1.683772,0.000098,0.000084,0.000012,0.000028,0.000054,0.000099,0.000018,0.000040,...,0.000004,0.000030,0.000023,0.000011,0.000031,0.000067,0.000013,0.000015,0.000011,0.000012
2602,6_c2262c60c000.csv,1.682825,0.000016,0.000063,0.000026,0.000051,0.000065,0.000031,0.000017,0.000082,...,0.000021,0.000032,0.000027,0.000038,0.000011,0.000033,0.000044,0.000043,0.000089,0.000081
2603,6_c2263c60c000.csv,1.683132,0.000058,0.000018,0.000073,0.000135,0.000018,0.000044,0.000053,0.000013,...,0.000025,0.000020,0.000014,0.000063,0.000013,0.000036,0.000072,0.000009,0.000008,0.000006

In [14]:
finite_Y

0       0
1       0
2       0
3       0
4       0
       ..
2599    6
2600    6
2601    6
2602    6
2603    6
Name: label, Length: 2604, dtype: int64

### Data Prep

In [15]:
from sklearn.model_selection import train_test_split

clean_X = finite_X.drop(["0", "ID"], axis = 1)

clean_X = clean_X.reset_index(drop=True)

x_train, x_test, y_train, y_test = train_test_split(clean_X, finite_Y, test_size=0.2, random_state=0, stratify=finite_Y)

In [16]:
x_train.shape

(2083, 5000)

In [17]:
np.max(x_train)

1       0.002619
2       0.002990
3       0.002766
4       0.003019
5       0.002523
          ...
4996    0.000129
4997    0.000102
4998    0.000118
4999    0.000102
5000    0.000122
Length: 5000, dtype: float64

In [18]:
n_train = np.reshape(np.linalg.norm(x_train, axis = 1), (-1, 1))
n_test = np.reshape(np.linalg.norm(x_test, axis = 1), (-1,1))

In [19]:
normalized_x_train = (x_train / n_train) * 100
normalized_x_test = (x_test / n_test) * 100

In [20]:
np.max(normalized_x_train)

1       0.593805
2       0.632208
3       0.627087
4       0.796226
5       0.775644
          ...
4996    0.036487
4997    0.032049
4998    0.038619
4999    0.034238
5000    0.038307
Length: 5000, dtype: float64

In [21]:
np.max(normalized_x_test)

1       0.642632
2       0.451384
3       0.781951
4       0.404424
5       0.521063
          ...
4996    0.028966
4997    0.031039
4998    0.033520
4999    0.032234
5000    0.044583
Length: 5000, dtype: float64

In [22]:
y_train = np.reshape(np.array(y_train), (-1,1))
y_test = np.reshape(np.array(y_test), (-1,1))

In [23]:
from sklearn.preprocessing import OneHotEncoder

o = OneHotEncoder()
y_train_onehot = o.fit_transform(y_train).toarray()
y_test_onehot = o.transform(y_test).toarray()

### Model Building starts

In [24]:
import tensorflow as tf

from keras.layers import Dense
from keras import Sequential
from keras.losses import SparseCategoricalCrossentropy, CategoricalCrossentropy

In [25]:
model = Sequential([Dense(2500, activation = "relu"),
                    Dense(1200, activation = "relu"),
                    Dense(600, activation = "relu"),
                    Dense(300, activation = "relu"),
                    Dense(150, activation = "relu"),
                    Dense(75, activation = "relu"),
                    Dense(30, activation = "relu"),
                    Dense(7, activation = "softmax")])

model.compile(loss=SparseCategoricalCrossentropy(), optimizer = "adam",metrics=["accuracy"])

### PCA for reducing vector length

In [76]:
from sklearn.decomposition import PCA

test_p = PCA()
test_p.fit(normalized_x_train)

PCA()

In [99]:
np.where(np.cumsum(test_p.explained_variance_ratio_) <= 0.9999999)

(array([   0,    1,    2, ..., 1914, 1915, 1916], dtype=int64),)

In [100]:
p = PCA(n_components=1917)
p.fit(normalized_x_train)

PCA(n_components=1917)

In [101]:
compressed_x_train = p.transform(normalized_x_train)
compressed_x_test = p.transform(normalized_x_test)

In [102]:
compressed_x_train.shape

(2083, 1917)

In [104]:
from sklearn.neighbors import KNeighborsClassifier

newmodel = KNeighborsClassifier(n_neighbors=11)

newmodel.fit(compressed_x_train, y_train)

C:\Users\Lohith\miniconda3\envs\tensor\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=11)

In [105]:
from sklearn.metrics import accuracy_score
accuracy_score(newmodel.predict(compressed_x_test), y_test)

0.54510556621881

## Ideas
### Build multiple models with decent individual accuracy and do Ensemble
### Decision Tree Classfier
### Random Forest